<?xml version="1.0"?>
<!DOCTYPE Report
[
<!ELEMENT Report (General ,(Doc|BPT)) >
<!ATTLIST Report ver CDATA #REQUIRED tmZone CDATA #REQUIRED>

<!ELEMENT General ( DocLocation ) >
<!ATTLIST General productName CDATA #REQUIRED productVer CDATA #REQUIRED os CDATA #REQUIRED host CDATA #REQUIRED qcserver CDATA #IMPLIED qcproject CDATA #IMPLIED SolManSolutionId CDATA #IMPLIED SolManProjectId CDATA #IMPLIED SolManTestPlanId CDATA #IMPLIED SolManTestPackageId CDATA #IMPLIED SolManUserInfoData CDATA #IMPLIED  >

<!ELEMENT BPT (DName,Res,DVer?,TSet?,TInst?,NodeArgs,AdditionalInfo*,Doc*) >
<!ATTLIST BPT rID ID #REQUIRED >

<!ELEMENT Doc (DName,ConfName?,Res,DVer?,TSet?,TInst?,RunType?,DT?,AdditionalInfo*,Step*,DIter*,Step*,Action*,Doc*,Summary?,TestMaintenanceSummary*,NodeArgs?) >
<!ATTLIST Doc rID ID #REQUIRED type (Test|BC|BPTWrapperTest|Flow|Group|Action) "Test" productName CDATA #REQUIRED BCIter CDATA #IMPLIED >

<!ELEMENT RunType ( #PCDATA )>
<!ATTLIST RunType fmStep (False|True) "False" batch (False|True) "False" upDesc (False|True) "False" upChk (False|True) "False" upAS (False|True) "False">

<!ELEMENT DName ( #PCDATA ) >

<!ELEMENT ConfName ( #PCDATA ) >

<!ELEMENT Res ( #PCDATA ) >

<!ELEMENT AdditionalInfo (AdditionalDataName,AdditionalDataValue ) >

<!ELEMENT AdditionalDataName ( #PCDATA ) >

<!ELEMENT AdditionalDataValue ( #PCDATA ) >

<!ELEMENT DVer ( #PCDATA ) >

<!ELEMENT TSet ( #PCDATA ) >

<!ELEMENT TInst ( #PCDATA ) >

<!ELEMENT DIter (Step*,Action+,Summary?,NodeArgs)>
<!ATTLIST DIter rID ID #REQUIRED iterID CDATA #REQUIRED>

<!ELEMENT DocLocation ( #PCDATA )>

<!ELEMENT Action (AName,AIter*,(Step|HtmlStep|Action)*, Summary,ActionMaintenanceSummary*, NodeArgs ) >
<!ATTLIST Action rID ID #REQUIRED>

<!ELEMENT AIter ((Step|HtmlStep|Action)*,DataMapping?, Summary?,NodeArgs) >
<!ATTLIST AIter rID ID #REQUIRED iterID CDATA #REQUIRED isCountable (False|True) "False" >

<!ELEMENT AName ( #PCDATA ) >

<!ELEMENT TestMaintenanceSummary (ActionMaintenanceSummary*) >
<!ATTLIST TestMaintenanceSummary ObjectsAdded CDATA #REQUIRED ObjectsUpdated CDATA #REQUIRED StepsUpdated CDATA #REQUIRED StepsComments CDATA #REQUIRED><!ELEMENT ActionMaintenanceSummary (ObjectChange* ) >
<!ATTLIST ActionMaintenanceSummary Action CDATA #REQUIRED Objects CDATA #REQUIRED Updated CDATA #REQUIRED LinesTotal CDATA #REQUIRED Added CDATA #REQUIRED LinesUpdated CDATA #REQUIRED>

<!ELEMENT ObjectChange  (Hierarchy, PropertyChangeList* ) >
<!ATTLIST ObjectChange Operation CDATA #IMPLIED OriginalRepository CDATA #IMPLIED>

<!ELEMENT PropertyChangeList (PropertyDef*) >

<!ELEMENT PropertyDef (OriginalValue, NewValue) >
<!ATTLIST PropertyDef PropName CDATA #REQUIRED OriginRegularExpression (True|False) "False" NewRegularExpression (True|False) "False" AddedProperty (True|False) "False" >

<!ELEMENT OriginalValue ( #PCDATA )>

<!ELEMENT NewValue ( #PCDATA )>

<!ELEMENT Hierarchy  (ObjectName, Hierarchy*) >
<!ATTLIST Hierarchy MicClass CDATA #REQUIRED>

<!ELEMENT ObjectName  ( #PCDATA ) >

<!ELEMENT Step (Obj,Details,Time,TimeTick* ,(Step|HtmlStep|Doc)*, DataMapping?, NodeArgs) >
<!ATTLIST Step rID ID #REQUIRED retval CDATA #IMPLIED>

<!ELEMENT HtmlStep (HTML,TimeTick*,(Step|HtmlStep|Doc)*,NodeArgs) >
<!ATTLIST HtmlStep rID ID #REQUIRED >

<!ELEMENT Obj ( #PCDATA ) >
<!ATTLIST Obj plainTxt (False|True) "True">

<!ELEMENT Details ( #PCDATA ) >
<!ATTLIST Details plainTxt (False|True) "True">

<!ELEMENT Time ( #PCDATA ) >

<!ELEMENT HTML ( #PCDATA ) >

<!ELEMENT Disp ( #PCDATA ) >

<!ELEMENT TimeTick ( #PCDATA ) >

<!ELEMENT DataMapping ( DataMappedItem* )>
<!ELEMENT DataMappedItem EMPTY >
<!ATTLIST DataMappedItem dsName CDATA #REQUIRED >
<!ATTLIST DataMappedItem rowId CDATA #REQUIRED >

<!ELEMENT NodeArgs (Disp,TopPane?,BtmPane?,ExtendedInfo? )>
<!ATTLIST NodeArgs eType CDATA #REQUIRED icon CDATA #REQUIRED nRep CDATA #REQUIRED UserNote CDATA #IMPLIED filter (False|True) "True">
<!ATTLIST NodeArgs status (Passed|Failed|Done|Warning|Information) "Done">
<!ATTLIST NodeArgs iconSel CDATA #IMPLIED nType CDATA #IMPLIED MovieMarker CDATA "">
<!ATTLIST NodeArgs Source CDATA #IMPLIED SourceLine CDATA #IMPLIED StepFlowItemKey CDATA #IMPLIED >

<!ELEMENT TopPane (Path)>

<!ELEMENT BtmPane ( (Path|WR)?,ASHilite?)>
<!ATTLIST BtmPane vType CDATA "HTML">

<!ELEMENT Path ( #PCDATA ) >

<!ELEMENT ASHilite ( #PCDATA ) >

<!ELEMENT WR ( #PCDATA ) >

<!ELEMENT ExtendedInfo ( StepData ) >

<!ATTLIST ExtendedInfo StepType CDATA #REQUIRED>
<!ELEMENT DT (NodeArgs) >
<!ATTLIST DT rID ID #REQUIRED>

<!ELEMENT Summary (Param*)>
<!ATTLIST Summary sTime CDATA #IMPLIED eTime CDATA #IMPLIED passed CDATA #IMPLIED failed CDATA #IMPLIED warnings CDATA #IMPLIED retval CDATA #IMPLIED stopped (False|True) "False" >

<!ELEMENT Param (ParamName,ParamVal)+ >
<!ATTLIST Param paramInOut (In|Out) "In">

<!ELEMENT ParamName ( #PCDATA ) >

<!ELEMENT ParamVal ( #PCDATA ) >

]
>
<Report ver="2.0" tmZone="India Standard Time">
<General productName="HP Unified Functional Testing" productVer="12.02" os="Windows 7" host="NALLI-PC"><DocLocation><![CDATA[C:\Automation_TCRM\kptravels\TEST\Test]]></DocLocation></General>
<Doc rID="T1"   productName= "HP Unified Functional Testing"  >
<DName><![CDATA[Test]]></DName>
<Res><![CDATA[Res1]]></Res>
<DT rID="T2">
<NodeArgs eType="Table" icon="2" nRep="4" filter="False" >
<Disp><![CDATA[Run-Time Data Table]]></Disp>
<BtmPane vType="Table" >
<Path><![CDATA[Default.xls]]></Path>
</BtmPane>
</NodeArgs>
</DT>
<Action rID="T3">
<AName><![CDATA[kpn_travels]]></AName>
<Step rID="T4">
<Obj ><![CDATA[1]]></Obj>
<Details ><![CDATA[Expected Results: Expected: Variable assignment done SuccessfullyActual Results: Actual: Variable assignment done Successfully]]></Details>
<Time><![CDATA[10/14/2016 - 20:11:26]]></Time>
<TimeTick>1476456086</TimeTick>
<NodeArgs eType="User" icon="4" nRep="7" status="Passed" >
<Disp><![CDATA[1]]></Disp>
</NodeArgs>
</Step>
<Step rID="T5">
<Obj ><![CDATA[2]]></Obj>
<Details ><![CDATA[Expected Results: Expected: Load datasheet to the runtime datatableActual Results: Actual: Datasheet sheet is loaded to the runtime datatable]]></Details>
<Time><![CDATA[10/14/2016 - 20:11:26]]></Time>
<TimeTick>1476456086</TimeTick>
<NodeArgs eType="User" icon="4" nRep="8" status="Passed" >
<Disp><![CDATA[2]]></Disp>
</NodeArgs>
</Step>
<Step rID="T6">
<Obj ><![CDATA[3]]></Obj>
<Details ><![CDATA[Expected Results: Expected: Variable assignment done SuccessfullyActual Results: Actual: Variable assignment done Successfully]]></Details>
<Time><![CDATA[10/14/2016 - 20:11:29]]></Time>
<TimeTick>1476456089</TimeTick>
<NodeArgs eType="User" icon="4" nRep="9" status="Passed" >
<Disp><![CDATA[3]]></Disp>
</NodeArgs>
</Step>
<Step rID="T7">
<Obj ><![CDATA[4]]></Obj>
<Details ><![CDATA[Expected Results: Expected: Variable assignment done Successfully for the Datatable iteration NoActual Results: Actual: Variable assignment done Successfully for the Datatable iteration No: 2]]></Details>
<Time><![CDATA[10/14/2016 - 20:11:29]]></Time>
<TimeTick>1476456089</TimeTick>
<NodeArgs eType="User" icon="4" nRep="10" status="Passed" >
<Disp><![CDATA[4]]></Disp>
</NodeArgs>
</Step>
<Step rID="T8">
<Obj ><![CDATA[5]]></Obj>
<Details ><![CDATA[Expected Results: Expected: Variable assignment done Successfully for the random nameActual Results: Actual: Variable assignment done Successfully for the random name: Travel_1410201129]]></Details>
<Time><![CDATA[10/14/2016 - 20:11:29]]></Time>
<TimeTick>1476456089</TimeTick>
<NodeArgs eType="User" icon="4" nRep="11" status="Passed" >
<Disp><![CDATA[5]]></Disp>
</NodeArgs>
</Step>
<Step rID="T9">
<Obj ><![CDATA[7]]></Obj>
<Details ><![CDATA[Expected Results: Expected: Execute userscript:Set WshShell=CreateObject("WScript.Shell")
WshShell.RegWrite "HKCU\Software\Microsoft\Internet Explorer\New Windows\PopupMgr","1","REG_DWORD"Actual Results: Actual: User Script Executed Successfully]]></Details>
<Time><![CDATA[10/14/2016 - 20:11:29]]></Time>
<TimeTick>1476456089</TimeTick>
<NodeArgs eType="User" icon="4" nRep="12" status="Passed" >
<Disp><![CDATA[7]]></Disp>
</NodeArgs>
</Step>
<Step rID="T10">
<Obj plainTxt="False" ><![CDATA[SystemUtil]]></Obj>
<Details plainTxt="False" ><![CDATA[SystemUtil]]></Details>
<Time><![CDATA[10/14/2016 - 20:11:59]]></Time>
<TimeTick>1476456119</TimeTick>
<Step rID="T11">
<Obj plainTxt="False" ><![CDATA[Run "iexplore.exe",1]]></Obj>
<Details plainTxt="False" ><![CDATA[Run "iexplore.exe",1]]></Details>
<Time><![CDATA[10/14/2016 - 20:11:59]]></Time>
<TimeTick>1476456119</TimeTick>
<NodeArgs eType="Replay" icon="5" nRep="16" status="Passed" Source="C:\Automation_TCRM\kptravels\LIB\kptravels_FunctionLibrary.txt" SourceLine="16" >
<Disp><![CDATA[Run "iexplore.exe",1]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Replay" icon="5" nRep="15" status="Passed" Source="C:\Automation_TCRM\kptravels\LIB\kptravels_FunctionLibrary.txt" SourceLine="16" >
<Disp><![CDATA[SystemUtil]]></Disp>
</NodeArgs>
</Step>
<Step rID="T12">
<Obj ><![CDATA[8]]></Obj>
<Details ><![CDATA[Expected Results: Expected: Execute the function  Successfully with params: LaunchApp intStepNo , StrDatasheetnameActual Results: Actual: Executed the function  Successfully with params: LaunchApp intStepNo , StrDatasheetname]]></Details>
<Time><![CDATA[10/14/2016 - 20:18:05]]></Time>
<TimeTick>1476456485</TimeTick>
<NodeArgs eType="User" icon="4" nRep="17" status="Passed" Source="C:\Automation_TCRM\kptravels\LIB\FunctionLibrary.txt" SourceLine="1780" >
<Disp><![CDATA[8]]></Disp>
</NodeArgs>
</Step>
<Step rID="T13">
<Obj plainTxt="False" ><![CDATA[KPNHOME]]></Obj>
<Details plainTxt="False" ><![CDATA[Browser]]></Details>
<Time><![CDATA[10/14/2016 - 20:21:35]]></Time>
<TimeTick>1476456695</TimeTick>
<Step rID="T14">
<Obj plainTxt="False" ><![CDATA[KPN Travels : Home]]></Obj>
<Details plainTxt="False" ><![CDATA[Page]]></Details>
<Time><![CDATA[10/14/2016 - 20:21:36]]></Time>
<TimeTick>1476456696</TimeTick>
<Step rID="T15">
<Obj plainTxt="False" ><![CDATA[wlk_Signin_KPNHOME.Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object does not exist"]]></Details>
<Time><![CDATA[10/14/2016 - 20:21:36]]></Time>
<TimeTick>1476456696</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="39" Source="C:\Automation_TCRM\kptravels\LIB\FunctionLibrary.txt" SourceLine="835" >
<Disp><![CDATA[wlk_Signin_KPNHOME.Exist]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="7" nRep="38" Source="C:\Automation_TCRM\kptravels\LIB\FunctionLibrary.txt" SourceLine="835" >
<Disp><![CDATA[KPN Travels : Home]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="6" nRep="37" Source="C:\Automation_TCRM\kptravels\LIB\FunctionLibrary.txt" SourceLine="835" >
<Disp><![CDATA[KPNHOME]]></Disp>
</NodeArgs>
</Step>
<Step rID="T16">
<Obj ><![CDATA[9.1]]></Obj>
<Details ><![CDATA[Expected Results: Expected: Object wlk_Signin_KPNHOME Exists Actual Results: Actual: User Script was NOT executed successfully; Err Description: Unterminated string constant]]></Details>
<Time><![CDATA[10/14/2016 - 20:21:37]]></Time>
<TimeTick>1476456697</TimeTick>
<NodeArgs eType="User" icon="4" nRep="40" status="Failed" Source="C:\Automation_TCRM\kptravels\LIB\FunctionLibrary.txt" SourceLine="835" >
<Disp><![CDATA[9.1]]></Disp>
</NodeArgs>
</Step>
<Step rID="T17">
<Obj ><![CDATA[9.1]]></Obj>
<Details ><![CDATA[Expected: Step executed without errors Actual: Errors were found, Exiting Test Case  :Unterminated string constant]]></Details>
<Time><![CDATA[10/14/2016 - 20:21:37]]></Time>
<TimeTick>1476456697</TimeTick>
<NodeArgs eType="User" icon="4" nRep="41" status="Failed" Source="C:\Automation_TCRM\kptravels\LIB\FunctionLibrary.txt" SourceLine="835" >
<Disp><![CDATA[9.1]]></Disp>
</NodeArgs>
</Step>
<Step rID="T18">
<Obj ><![CDATA[9]]></Obj>
<Details ><![CDATA[Expected Results: Expected: Execute the function  Successfully with params: Signin intStepNo , StrDatasheetnameActual Results: Actual: Executed the function  Successfully with params: Signin intStepNo , StrDatasheetname]]></Details>
<Time><![CDATA[10/14/2016 - 20:21:37]]></Time>
<TimeTick>1476456697</TimeTick>
<NodeArgs eType="User" icon="4" nRep="42" status="Passed" Source="C:\Automation_TCRM\kptravels\LIB\FunctionLibrary.txt" SourceLine="835" >
<Disp><![CDATA[9]]></Disp>
</NodeArgs>
</Step>
<Step rID="T19">
<Obj plainTxt="False" ><![CDATA[KPNHOME]]></Obj>
<Details plainTxt="False" ><![CDATA[Browser]]></Details>
<Time><![CDATA[10/14/2016 - 20:21:39]]></Time>
<TimeTick>1476456699</TimeTick>
<Step rID="T20">
<Obj plainTxt="False" ><![CDATA[KPN Travels : My Account]]></Obj>
<Details plainTxt="False" ><![CDATA[Page]]></Details>
<Time><![CDATA[10/14/2016 - 20:21:39]]></Time>
<TimeTick>1476456699</TimeTick>
<Step rID="T21">
<Obj plainTxt="False" ><![CDATA[wlk_BookTicket_MyAccount.Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object does not exist"]]></Details>
<Time><![CDATA[10/14/2016 - 20:21:39]]></Time>
<TimeTick>1476456699</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="64" Source="C:\Automation_TCRM\kptravels\LIB\FunctionLibrary.txt" SourceLine="835" >
<Disp><![CDATA[wlk_BookTicket_MyAccount.Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T22">
<Obj plainTxt="False" ><![CDATA[wlk_BookTicket_MyAccount.Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object does not exist"]]></Details>
<Time><![CDATA[10/14/2016 - 20:21:41]]></Time>
<TimeTick>1476456701</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="84" Source="C:\Automation_TCRM\kptravels\LIB\FunctionLibrary.txt" SourceLine="835" >
<Disp><![CDATA[wlk_BookTicket_MyAccount.Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T23">
<Obj plainTxt="False" ><![CDATA[wlk_BookTicket_MyAccount.Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object does not exist"]]></Details>
<Time><![CDATA[10/14/2016 - 20:21:43]]></Time>
<TimeTick>1476456703</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="104" Source="C:\Automation_TCRM\kptravels\LIB\FunctionLibrary.txt" SourceLine="835" >
<Disp><![CDATA[wlk_BookTicket_MyAccount.Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T24">
<Obj plainTxt="False" ><![CDATA[wlk_BookTicket_MyAccount.Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object does not exist"]]></Details>
<Time><![CDATA[10/14/2016 - 20:21:45]]></Time>
<TimeTick>1476456705</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="124" Source="C:\Automation_TCRM\kptravels\LIB\FunctionLibrary.txt" SourceLine="835" >
<Disp><![CDATA[wlk_BookTicket_MyAccount.Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T25">
<Obj plainTxt="False" ><![CDATA[wlk_BookTicket_MyAccount.Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object does not exist"]]></Details>
<Time><![CDATA[10/14/2016 - 20:21:48]]></Time>
<TimeTick>1476456708</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="144" Source="C:\Automation_TCRM\kptravels\LIB\FunctionLibrary.txt" SourceLine="835" >
<Disp><![CDATA[wlk_BookTicket_MyAccount.Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T26">
<Obj plainTxt="False" ><![CDATA[wlk_BookTicket_MyAccount.Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object does not exist"]]></Details>
<Time><![CDATA[10/14/2016 - 20:21:50]]></Time>
<TimeTick>1476456710</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="164" Source="C:\Automation_TCRM\kptravels\LIB\FunctionLibrary.txt" SourceLine="835" >
<Disp><![CDATA[wlk_BookTicket_MyAccount.Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T27">
<Obj plainTxt="False" ><![CDATA[wlk_BookTicket_MyAccount.Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object does not exist"]]></Details>
<Time><![CDATA[10/14/2016 - 20:21:52]]></Time>
<TimeTick>1476456712</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="184" Source="C:\Automation_TCRM\kptravels\LIB\FunctionLibrary.txt" SourceLine="835" >
<Disp><![CDATA[wlk_BookTicket_MyAccount.Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T28">
<Obj plainTxt="False" ><![CDATA[wlk_BookTicket_MyAccount.Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object does not exist"]]></Details>
<Time><![CDATA[10/14/2016 - 20:21:54]]></Time>
<TimeTick>1476456714</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="204" Source="C:\Automation_TCRM\kptravels\LIB\FunctionLibrary.txt" SourceLine="835" >
<Disp><![CDATA[wlk_BookTicket_MyAccount.Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T29">
<Obj plainTxt="False" ><![CDATA[wlk_BookTicket_MyAccount.Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object does not exist"]]></Details>
<Time><![CDATA[10/14/2016 - 20:21:57]]></Time>
<TimeTick>1476456717</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="224" Source="C:\Automation_TCRM\kptravels\LIB\FunctionLibrary.txt" SourceLine="835" >
<Disp><![CDATA[wlk_BookTicket_MyAccount.Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T30">
<Obj plainTxt="False" ><![CDATA[wlk_BookTicket_MyAccount.Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object does not exist"]]></Details>
<Time><![CDATA[10/14/2016 - 20:21:59]]></Time>
<TimeTick>1476456719</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="244" Source="C:\Automation_TCRM\kptravels\LIB\FunctionLibrary.txt" SourceLine="835" >
<Disp><![CDATA[wlk_BookTicket_MyAccount.Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T31">
<Obj plainTxt="False" ><![CDATA[wlk_BookTicket_MyAccount.Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object does not exist"]]></Details>
<Time><![CDATA[10/14/2016 - 20:22:01]]></Time>
<TimeTick>1476456721</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="264" Source="C:\Automation_TCRM\kptravels\LIB\FunctionLibrary.txt" SourceLine="835" >
<Disp><![CDATA[wlk_BookTicket_MyAccount.Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T32">
<Obj plainTxt="False" ><![CDATA[wlk_BookTicket_MyAccount.Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object does not exist"]]></Details>
<Time><![CDATA[10/14/2016 - 20:22:03]]></Time>
<TimeTick>1476456723</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="284" Source="C:\Automation_TCRM\kptravels\LIB\FunctionLibrary.txt" SourceLine="835" >
<Disp><![CDATA[wlk_BookTicket_MyAccount.Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T33">
<Obj plainTxt="False" ><![CDATA[wlk_BookTicket_MyAccount.Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object does not exist"]]></Details>
<Time><![CDATA[10/14/2016 - 20:22:06]]></Time>
<TimeTick>1476456726</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="304" Source="C:\Automation_TCRM\kptravels\LIB\FunctionLibrary.txt" SourceLine="835" >
<Disp><![CDATA[wlk_BookTicket_MyAccount.Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T34">
<Obj plainTxt="False" ><![CDATA[Stop Run]]></Obj>
<Details plainTxt="False" ><![CDATA[Run stopped by user.]]></Details>
<Time><![CDATA[10/14/2016 - 20:22:06]]></Time>
<TimeTick>1476456726</TimeTick>
<NodeArgs eType="General" icon="9" nRep="305" >
<Disp><![CDATA[Stop Run]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="7" nRep="63" Source="C:\Automation_TCRM\kptravels\LIB\FunctionLibrary.txt" SourceLine="835" >
<Disp><![CDATA[KPN Travels : My Account]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="6" nRep="62" Source="C:\Automation_TCRM\kptravels\LIB\FunctionLibrary.txt" SourceLine="835" >
<Disp><![CDATA[KPNHOME]]></Disp>
</NodeArgs>
</Step>
<Summary sTime="10/14/2016 - 20:11:05" eTime="10/14/2016 - 20:22:09" passed="9" failed="2" warnings="0" ></Summary>
<NodeArgs eType="StartAction" icon="3" nRep="6" status="Failed" >
<Disp><![CDATA[kpn_travels Summary]]></Disp>
</NodeArgs>
</Action>
<Step rID="T35">
<Obj plainTxt="False" ><![CDATA[Stop Run]]></Obj>
<Details plainTxt="False" ><![CDATA[Run stopped by user.]]></Details>
<Time><![CDATA[10/14/2016 - 20:22:09]]></Time>
<TimeTick>1476456729</TimeTick>
<NodeArgs eType="General" icon="10" nRep="307" >
<Disp><![CDATA[Stop Run]]></Disp>
</NodeArgs>
</Step>
<Summary sTime="10/14/2016 - 20:11:00" eTime="10/14/2016 - 20:22:09" passed="9" failed="2" warnings="0" stopped="True" ><Param ><ParamName><![CDATA[xyz]]></ParamName><ParamVal><![CDATA[]]></ParamVal>
</Param>
</Summary>
<NodeArgs eType="StartTest" icon="1" nRep="3" status="Failed" >
<Disp><![CDATA[Test Test Summary]]></Disp>
</NodeArgs>
</Doc>
</Report>